apiVersion: v1
kind: Namespace
metadata:
  name: pokedex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pokedex
  namespace: pokedex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
  namespace: pokedex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
  namespace: pokedex
spec:
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: pokedex
      containers:
        - name: pokedex
          image: jacobmammoliti/pokedex:latest
          args:
            - -port=8080
            - -host=127.0.0.1
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: static-client
  namespace: pokedex
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
    'consul.hashicorp.com/connect-service-upstreams': 'pokedex:8080'
spec:
  containers:
    - name: static-client
      image: tutum/curl:latest
      command: ['/bin/sh', '-c', '--']
      args: ['while true; do sleep 30; done;']
  serviceAccountName: static-client