---
apiVersion: v1
kind: Namespace
metadata:
  name: pokedex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
  namespace: pokedex
  labels:
    app: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
      - name: pokedex
        image: jacobmammoliti/pokedex:latest
        args:
            - -port=8080
            - -host=127.0.0.1
        ports:
        - containerPort: 8080
